CREATE SCHEMA STAGE;

CREATE TABLE STAGE.PUNCHING_TELEMETRY (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	SPINDLE_SPEED_RPM TEXT,
	FEED_RATE_MM_MIN TEXT,
	VIBRATION_G TEXT,
	TEMPERATURE_C TEXT,
	POWER_KW TEXT,
	TOOL_WEAR_PCT TEXT
);

CREATE TABLE STAGE.BENDING_TELEMETRY (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	BEND_ANGLE_DEG TEXT,
	HYDRAULIC_PRESSURE_BAR TEXT,
	FORCE_TON TEXT,
	CYCLE_TIME_SEC TEXT,
	POWER_KW TEXT
);

CREATE TABLE STAGE.WELDING_TELEMETRY (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	WELDING_CURRENT_AMP TEXT,
	WELDING_VOLTAGE_V TEXT,
	GAS_FLOW_L_MIN TEXT,
	WIRE_FEED_SPEED_M_MIN TEXT,
	TEMPERATURE_C TEXT,
	POWER_KW TEXT
);

CREATE TABLE STAGE.POWDER_COATING_TELEMETRY (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	OVEN_TEMPERATURE_C TEXT,
	CONVEYOR_SPEED_M_MIN TEXT,
	POWDER_FLOW_G_MIN TEXT,
	AIR_PRESSURE_BAR TEXT,
	HUMIDITY_PCT TEXT,
	POWER_KW TEXT
);

CREATE TABLE STAGE.PACKAGING_TELEMETRY (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	UNITS_PACKED_PER_MIN TEXT,
	BARCODE_SCAN_SUCCESS_RATE TEXT,
	LABEL_PRINTER_TEMP_C TEXT,
	AIR_PRESSURE_BAR TEXT,
	CONVEYOR_SPEED_M_MIN TEXT,
	POWER_KW TEXT
);

CREATE TABLE STAGE.MAINTENANCE_EVENTS (
	MAINTENANCE_ID TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	MAINTENANCE_TYPE TEXT,
	DOWNTIME_REASON TEXT,
	START_TIME TEXT,
	END_TIME TEXT,
	DOWNTIME_MIN TEXT
);

CREATE TABLE STAGE.PRODUCTION_ORDERS (
	ORDER_ID TEXT,
	PRODUCT_ID TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	PLANNED_QTY TEXT,
	ACTUAL_QTY TEXT,
	SCRAP_QTY TEXT,
	SHIFT TEXT,
	START_TIME TEXT,
	END_TIME TEXT
);

CREATE TABLE STAGE.BREAKS (SHIFT TEXT, BREAK_START TEXT, BREAK_END TEXT);

CREATE TABLE STAGE.MACHINE_STATES (STATUS TEXT, MEANING TEXT);

CREATE TABLE STAGE.OPERATIONS (
	ORDER_ID TEXT,
	PRODUCT_ID TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	PLANNED_QTY TEXT,
	ACTUAL_QTY TEXT,
	SCRAP_QTY TEXT,
	SHIFT TEXT
);

CREATE TABLE STAGE.OPERATORS (
	WORK_STATION_ID TEXT,
	WORK_STATION TEXT,
	PRODUCT_NAME TEXT,
	OPERATION_SEQUENCE TEXT,
	IDEAL_CYCLE_TIME_SEC TEXT
);

CREATE TABLE STAGE.PRODUCTS (
	PRODUCT_ID TEXT,
	PRODUCT_NAME TEXT,
	STANDARD_CYCLE_TIME_SEC TEXT,
	TARGET_SCRAP_RATE TEXT
);

CREATE TABLE STAGE.SHIFTS (SHIFT TEXT, START_TIME TEXT, END_TIME TEXT);
