CREATE SCHEMA CLEAN;

CREATE TABLE CLEAN.WORK_STATIONS (
	WORK_STATION_ID TEXT PRIMARY KEY,
	WORK_STATION TEXT
);

CREATE TABLE CLEAN.MACHINE_STATES (STATUS TEXT PRIMARY KEY, MEANING TEXT);

CREATE TABLE CLEAN.OPERATORS (
	OPERATOR_ID TEXT PRIMARY KEY,
	NAME TEXT,
	ASSIGNED_STATION_ID TEXT,
	ASSIGNED_STATION TEXT,
	SKILL_LEVEL TEXT,
	SHIFT CHAR(1)
);

CREATE TABLE CLEAN.PRODUCTS (
	PRODUCT_ID TEXT PRIMARY KEY,
	PRODUCT_NAME TEXT,
	STANDARD_CYCLE_TIME_SEC NUMERIC(3),
	TARGET_SCRAP_RATE NUMERIC(3, 2)
);

CREATE TABLE CLEAN.SHIFTS (
	SHIFT CHAR(1) PRIMARY KEY,
	START_TIME TIME,
	END_TIME TIME
);

CREATE TABLE CLEAN.OPERATIONS (
	WORK_STATION_ID TEXT,
	WORK_STATION TEXT,
	PRODUCT_NAME TEXT,
	OPERATION_SEQUENCE NUMERIC(2),
	IDEAL_CYCLE_TIME_SEC NUMERIC(3)
);

CREATE TABLE CLEAN.PUNCHING_TELEMETRY (
	TELEMETRY_ID TEXT PRIMARY KEY,
	TIMESTAMP TIMESTAMP NOT NULL UNIQUE,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	MACHINE_STATUS TEXT NOT NULL REFERENCES CLEAN.MACHINE_STATES (STATUS),
	SPINDLE_SPEED_RPM NUMERIC(6, 2),
	FEED_RATE_MM_MIN NUMERIC(6, 2),
	VIBRATION_G NUMERIC(3, 2),
	TEMPERATURE_C NUMERIC(4, 2),
	POWER_KW NUMERIC(4, 2),
	TOOL_WEAR_PCT NUMERIC(4, 2)
);

CREATE TABLE CLEAN.BENDING_TELEMETRY (
	TELEMETRY_ID TEXT PRIMARY KEY,
	TIMESTAMP TIMESTAMP NOT NULL UNIQUE,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	MACHINE_STATUS TEXT NOT NULL REFERENCES CLEAN.MACHINE_STATES (STATUS),
	BEND_ANGLE_DEG NUMERIC(4, 2),
	HYDRAULIC_PRESSURE_BAR NUMERIC(5, 2),
	FORCE_TON NUMERIC(5, 2),
	CYCLE_TIME_SEC NUMERIC(5, 2),
	POWER_KW NUMERIC(4, 2)
);

CREATE TABLE CLEAN.WELDING_TELEMETRY (
	TELEMETRY_ID TEXT PRIMARY KEY,
	TIMESTAMP TIMESTAMP NOT NULL UNIQUE,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	MACHINE_STATUS TEXT NOT NULL REFERENCES CLEAN.MACHINE_STATES (STATUS),
	WELDING_CURRENT_AMP NUMERIC(5, 2),
	WELDING_VOLTAGE_V NUMERIC(4, 2),
	GAS_FLOW_L_MIN NUMERIC(4, 2),
	WIRE_FEED_SPEED_M_MIN NUMERIC(4, 2),
	TEMPERATURE_C NUMERIC(5, 2),
	POWER_KW NUMERIC(4, 2)
);

CREATE TABLE CLEAN.POWDER_COATING_TELEMETRY (
	TELEMETRY_ID TEXT PRIMARY KEY,
	TIMESTAMP TIMESTAMP NOT NULL UNIQUE,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	MACHINE_STATUS TEXT NOT NULL REFERENCES CLEAN.MACHINE_STATES (STATUS),
	OVEN_TEMPERATURE_C NUMERIC(5, 2),
	CONVEYOR_SPEED_M_MIN NUMERIC(3, 2),
	POWDER_FLOW_G_MIN NUMERIC(5, 2),
	AIR_PRESSURE_BAR NUMERIC(3, 2),
	HUMIDITY_PCT NUMERIC(4, 2),
	POWER_KW NUMERIC(4, 2)
);

CREATE TABLE CLEAN.PACKAGING_TELEMETRY (
	TELEMETRY_ID TEXT PRIMARY KEY,
	TIMESTAMP TIMESTAMP NOT NULL UNIQUE,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	MACHINE_STATUS TEXT NOT NULL REFERENCES CLEAN.MACHINE_STATES (STATUS),
	UNITS_PACKED_PER_MIN NUMERIC(4, 2),
	BARCODE_SCAN_SUCCESS_RATE NUMERIC(4, 2),
	LABEL_PRINTER_TEMP_C NUMERIC(4, 2),
	AIR_PRESSURE_BAR NUMERIC(3, 2),
	CONVEYOR_SPEED_M_MIN NUMERIC(4, 2),
	POWER_KW NUMERIC(4, 2)
);

CREATE TABLE CLEAN.MAINTENANCE_EVENTS (
	MAINTENANCE_ID TEXT PRIMARY KEY,
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	MAINTENANCE_TYPE TEXT,
	DOWNTIME_REASON TEXT,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	DOWNTIME_MIN INT
);

CREATE TABLE CLEAN.PRODUCTION_ORDERS (
	ORDER_ID TEXT PRIMARY KEY,
	PRODUCT_ID TEXT NOT NULL REFERENCES CLEAN.PRODUCTS (PRODUCT_ID),
	WORK_STATION_ID TEXT NOT NULL REFERENCES CLEAN.WORK_STATIONS (WORK_STATION_ID),
	OPERATOR_ID TEXT NOT NULL REFERENCES CLEAN.OPERATORS (OPERATOR_ID),
	PLANNED_QTY INTEGER NOT NULL,
	ACTUAL_QTY INTEGER NOT NULL,
	SCRAP_QTY INTEGER NOT NULL,
	SHIFT CHAR(1) NOT NULL REFERENCES CLEAN.SHIFTS (SHIFT),
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP
);