INSERT INTO
	CLEAN.MAINTENANCE_EVENTS (
		MAINTENANCE_ID,
		WORK_STATION_ID,
		OPERATOR_ID,
		MAINTENANCE_TYPE,
		DOWNTIME_REASON,
		START_TIME,
		END_TIME,
		DOWNTIME_MIN
	)
WITH
	TYPED AS (
		SELECT
			MAINTENANCE_ID,
			WORK_STATION_ID,
			OPERATOR_ID,
			MAINTENANCE_TYPE,
			DOWNTIME_REASON,
			CASE
				WHEN START_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN START_TIME::TIMESTAMP
			END AS START_TIME,
			CASE
				WHEN END_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN END_TIME::TIMESTAMP
			END AS END_TIME,
			CASE
				WHEN DOWNTIME_MIN ~ '^\d+(\.\d+)?$' THEN ROUND(DOWNTIME_MIN::NUMERIC)::INT
			END AS DOWNTIME_MIN
		FROM
			STAGE.MAINTENANCE_EVENTS
	),
	VALIDATED AS (
		SELECT
			T.*
		FROM
			TYPED T
			JOIN CLEAN.WORK_STATIONS W ON W.WORK_STATION_ID = T.WORK_STATION_ID
			JOIN CLEAN.OPERATORS O ON O.OPERATOR_ID = T.OPERATOR_ID
		WHERE
			T.MAINTENANCE_ID IS NOT NULL
			AND T.WORK_STATION_ID IS NOT NULL
			AND T.OPERATOR_ID IS NOT NULL
			AND T.START_TIME IS NOT NULL
			AND T.END_TIME IS NOT NULL
			AND T.DOWNTIME_MIN >= 0
			AND T.DOWNTIME_MIN <= 480
			AND T.END_TIME - T.START_TIME <= INTERVAL '8 hours'
			AND T.END_TIME > T.START_TIME
			AND T.DOWNTIME_MIN = ROUND(
				EXTRACT(
					EPOCH
					FROM
						(T.END_TIME - T.START_TIME)
				) / 60
			)
	),
	DEDUPED AS (
		SELECT
			*
		FROM
			(
				SELECT
					*,
					ROW_NUMBER() OVER (
						PARTITION BY
							WORK_STATION_ID,
							OPERATOR_ID,
							START_TIME
						ORDER BY
							MAINTENANCE_ID
					) AS RN
				FROM
					VALIDATED
			) X
		WHERE
			RN = 1
	)
SELECT
	MAINTENANCE_ID,
	WORK_STATION_ID,
	OPERATOR_ID,
	MAINTENANCE_TYPE,
	DOWNTIME_REASON,
	START_TIME,
	END_TIME,
	DOWNTIME_MIN
FROM
	DEDUPED
ON CONFLICT (MAINTENANCE_ID) DO NOTHING;

INSERT INTO
	CLEAN.PRODUCTION_ORDERS (
		ORDER_ID,
		PRODUCT_ID,
		WORK_STATION_ID,
		OPERATOR_ID,
		PLANNED_QTY,
		ACTUAL_QTY,
		SCRAP_QTY,
		SHIFT,
		START_TIME,
		END_TIME
	)
WITH
	VALIDATED AS (
		SELECT
			ORDER_ID,
			PRODUCT_ID,
			WORK_STATION_ID,
			OPERATOR_ID,
			PLANNED_QTY::INTEGER AS PLANNED_QTY,
			ACTUAL_QTY::INTEGER AS ACTUAL_QTY,
			SCRAP_QTY::INTEGER AS SCRAP_QTY,
			SHIFT,
			CASE
				WHEN START_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN START_TIME::TIMESTAMP
			END AS START_TIME,
			CASE
				WHEN END_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN END_TIME::TIMESTAMP
			END AS END_TIME
		FROM
			STAGE.PRODUCTION_ORDERS
		WHERE
			ORDER_ID IS NOT NULL
			AND START_TIME IS NOT NULL
			AND END_TIME IS NOT NULL
	)
SELECT
	V.ORDER_ID,
	V.PRODUCT_ID,
	V.WORK_STATION_ID,
	V.OPERATOR_ID,
	V.PLANNED_QTY,
	V.ACTUAL_QTY,
	V.SCRAP_QTY,
	V.SHIFT,
	V.START_TIME,
	V.END_TIME
FROM
	VALIDATED V
	JOIN CLEAN.PRODUCTS P ON P.PRODUCT_ID = V.PRODUCT_ID
	JOIN CLEAN.WORK_STATIONS W ON W.WORK_STATION_ID = V.WORK_STATION_ID
	JOIN CLEAN.OPERATORS O ON O.OPERATOR_ID = V.OPERATOR_ID
	JOIN CLEAN.SHIFTS S ON S.SHIFT = V.SHIFT
WHERE
	V.PLANNED_QTY > 0
	AND V.ACTUAL_QTY >= 0
	AND V.SCRAP_QTY >= 0
	AND V.ACTUAL_QTY <= V.PLANNED_QTY
	AND V.SCRAP_QTY <= V.ACTUAL_QTY
	AND V.PLANNED_QTY <= 10000
	AND V.ACTUAL_QTY <= 10000
	AND V.SCRAP_QTY <= 1000
	AND V.END_TIME - V.START_TIME <= INTERVAL '8 hours'
	AND V.END_TIME > V.START_TIME
ON CONFLICT (ORDER_ID) DO NOTHING;