CREATE SCHEMA AUDIT;

CREATE TABLE AUDIT.PRODUCTION_ORDERS_REJECTED (
	ORDER_ID TEXT,
	PRODUCT_ID TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	PLANNED_QTY TEXT,
	ACTUAL_QTY TEXT,
	SCRAP_QTY TEXT,
	SHIFT TEXT,
	START_TIME TEXT,
	END_TIME TEXT,
	REJECTION_REASON TEXT NOT NULL,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT.MAINTENANCE_EVENTS_REJECTED (
	MAINTENANCE_ID TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	MAINTENANCE_TYPE TEXT,
	DOWNTIME_REASON TEXT,
	START_TIME TEXT,
	END_TIME TEXT,
	DOWNTIME_MIN TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT.PUNCHING_TELEMETRY_REJECTED (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	SPINDLE_SPEED_RPM TEXT,
	FEED_RATE_MM_MIN TEXT,
	VIBRATION_G TEXT,
	TEMPERATURE_C TEXT,
	POWER_KW TEXT,
	TOOL_WEAR_PCT TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT.BENDING_TELEMETRY_REJECTED (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	BEND_ANGLE_DEG TEXT,
	HYDRAULIC_PRESSURE_BAR TEXT,
	FORCE_TON TEXT,
	CYCLE_TIME_SEC TEXT,
	POWER_KW TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT.WELDING_TELEMETRY_REJECTED (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	WELDING_CURRENT_AMP TEXT,
	WELDING_VOLTAGE_V TEXT,
	GAS_FLOW_L_MIN TEXT,
	WIRE_FEED_SPEED_M_MIN TEXT,
	TEMPERATURE_C TEXT,
	POWER_KW TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE AUDIT.POWDER_COATING_TELEMETRY_REJECTED (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	OVEN_TEMPERATURE_C TEXT,
	CONVEYOR_SPEED_M_MIN TEXT,
	POWDER_FLOW_G_MIN TEXT,
	AIR_PRESSURE_BAR TEXT,
	HUMIDITY_PCT TEXT,
	POWER_KW TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUDIT.PACKAGING_TELEMETRY_REJECTED (
	TELEMETRY_ID TEXT,
	TIMESTAMP TEXT,
	WORK_STATION_ID TEXT,
	OPERATOR_ID TEXT,
	SHIFT TEXT,
	MACHINE_STATUS TEXT,
	UNITS_PACKED_PER_MIN TEXT,
	BARCODE_SCAN_SUCCESS_RATE TEXT,
	LABEL_PRINTER_TEMP_C TEXT,
	AIR_PRESSURE_BAR TEXT,
	CONVEYOR_SPEED_M_MIN TEXT,
	POWER_KW TEXT,
	REJECTION_REASON TEXT,
	REJECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
	AUDIT.PRODUCTION_ORDERS_REJECTED (
		ORDER_ID,
		PRODUCT_ID,
		WORK_STATION_ID,
		OPERATOR_ID,
		PLANNED_QTY,
		ACTUAL_QTY,
		SCRAP_QTY,
		SHIFT,
		START_TIME,
		END_TIME,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			ORDER_ID,
			PRODUCT_ID,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			PLANNED_QTY,
			ACTUAL_QTY,
			SCRAP_QTY,
			START_TIME,
			END_TIME,
			CASE
				WHEN PLANNED_QTY ~ '^-?\d+$' THEN PLANNED_QTY::INT
			END AS PLANNED_QTY_INT,
			CASE
				WHEN ACTUAL_QTY ~ '^-?\d+$' THEN ACTUAL_QTY::INT
			END AS ACTUAL_QTY_INT,
			CASE
				WHEN SCRAP_QTY ~ '^-?\d+$' THEN SCRAP_QTY::INT
			END AS SCRAP_QTY_INT,
			CASE
				WHEN START_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN START_TIME::TIMESTAMP
			END AS START_TIME_TS,
			CASE
				WHEN END_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN END_TIME::TIMESTAMP
			END AS END_TIME_TS
		FROM
			STAGE.PRODUCTION_ORDERS
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN T.ORDER_ID IS NULL THEN 'null_order_id'
				WHEN T.PLANNED_QTY IS NULL THEN 'invalid_planned_qty'
				WHEN T.ACTUAL_QTY IS NULL THEN 'invalid_actual_qty'
				WHEN T.SCRAP_QTY IS NULL THEN 'invalid_scrap_qty'
				WHEN T.START_TIME IS NULL THEN 'invalid_start_time'
				WHEN T.END_TIME IS NULL THEN 'invalid_end_time'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.PRODUCTS PR
					WHERE
						PR.PRODUCT_ID = T.PRODUCT_ID
				) THEN 'invalid_product'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_workstation'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS SH
					WHERE
						SH.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN T.PLANNED_QTY_INT <= 0 THEN 'negative_planned_qty'
				WHEN T.ACTUAL_QTY_INT < 0 THEN 'negative_actual_qty'
				WHEN T.SCRAP_QTY_INT < 0 THEN 'negative_scrap_qty'
				WHEN T.ACTUAL_QTY_INT > T.PLANNED_QTY_INT THEN 'actual_gt_planned'
				WHEN T.SCRAP_QTY_INT > T.ACTUAL_QTY_INT THEN 'scrap_gt_actual'
				WHEN T.PLANNED_QTY_INT > 10000
				OR T.ACTUAL_QTY_INT > 10000
				OR T.SCRAP_QTY_INT > 1000 THEN 'impossible_quantity'
				WHEN T.END_TIME_TS <= T.START_TIME_TS THEN 'impossible_time'
				WHEN T.END_TIME_TS - T.START_TIME_TS > INTERVAL '8 hours' THEN 'more_than_8_hours'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	ORDER_ID,
	PRODUCT_ID,
	WORK_STATION_ID,
	OPERATOR_ID,
	PLANNED_QTY,
	ACTUAL_QTY,
	SCRAP_QTY,
	SHIFT,
	START_TIME,
	END_TIME,
	REJECTION_REASON
FROM
	REJECTED R
WHERE
	R.ORDER_ID IS NULL
	OR R.PLANNED_QTY IS NULL
	OR R.ACTUAL_QTY IS NULL
	OR R.SCRAP_QTY IS NULL
	OR R.START_TIME IS NULL
	OR R.END_TIME IS NULL
	OR NOT EXISTS (
		SELECT
			1
		FROM
			CLEAN.PRODUCTS PR
		WHERE
			PR.PRODUCT_ID = R.PRODUCT_ID
	)
	OR NOT EXISTS (
		SELECT
			1
		FROM
			CLEAN.WORK_STATIONS W
		WHERE
			W.WORK_STATION_ID = R.WORK_STATION_ID
	)
	OR NOT EXISTS (
		SELECT
			1
		FROM
			CLEAN.OPERATORS O
		WHERE
			O.OPERATOR_ID = R.OPERATOR_ID
	)
	OR NOT EXISTS (
		SELECT
			1
		FROM
			CLEAN.SHIFTS SH
		WHERE
			SH.SHIFT = R.SHIFT
	)
	OR R.PLANNED_QTY_INT <= 0
	OR R.ACTUAL_QTY_INT < 0
	OR R.SCRAP_QTY_INT < 0
	OR R.ACTUAL_QTY_INT > R.PLANNED_QTY_INT
	OR R.SCRAP_QTY_INT > R.ACTUAL_QTY_INT
	OR R.PLANNED_QTY_INT > 10000
	OR R.ACTUAL_QTY_INT > 10000
	OR R.SCRAP_QTY_INT > 1000
	OR R.END_TIME_TS <= R.START_TIME_TS
	OR R.END_TIME_TS - R.START_TIME_TS > INTERVAL '8 hours';

INSERT INTO
	AUDIT.MAINTENANCE_EVENTS_REJECTED (
		MAINTENANCE_ID,
		WORK_STATION_ID,
		OPERATOR_ID,
		MAINTENANCE_TYPE,
		DOWNTIME_REASON,
		START_TIME,
		END_TIME,
		DOWNTIME_MIN,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			MAINTENANCE_ID,
			WORK_STATION_ID,
			OPERATOR_ID,
			MAINTENANCE_TYPE,
			DOWNTIME_REASON,
			START_TIME AS RAW_START_TIME,
			END_TIME AS RAW_END_TIME,
			DOWNTIME_MIN AS RAW_DOWNTIME_MIN,
			CASE
				WHEN START_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN START_TIME::TIMESTAMP
			END AS TYPED_START_TIME,
			CASE
				WHEN END_TIME ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN END_TIME::TIMESTAMP
			END AS TYPED_END_TIME,
			CASE
				WHEN DOWNTIME_MIN ~ '^-?\d+$' THEN DOWNTIME_MIN::INT
			END AS TYPED_DOWNTIME_MIN
		FROM
			STAGE.MAINTENANCE_EVENTS
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN T.MAINTENANCE_ID IS NULL THEN 'null_maintenance_id'
				WHEN T.WORK_STATION_ID IS NULL THEN 'null_work_station_id'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN T.OPERATOR_ID IS NULL THEN 'null_operator_id'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN T.RAW_START_TIME IS NULL THEN 'invalid_start_time'
				WHEN T.RAW_END_TIME IS NULL THEN 'invalid_end_time'
				WHEN T.RAW_DOWNTIME_MIN IS NULL THEN 'invalid_downtime_min'
				WHEN T.TYPED_DOWNTIME_MIN < 0 THEN 'negative_downtime'
				WHEN T.TYPED_DOWNTIME_MIN > 480 THEN 'extreme_downtime'
				WHEN T.TYPED_END_TIME <= T.TYPED_START_TIME THEN 'end_before_start'
				WHEN T.TYPED_END_TIME - T.TYPED_START_TIME > INTERVAL '8 hours' THEN 'more_than_8_hours'
				WHEN T.TYPED_DOWNTIME_MIN <> ROUND(
					EXTRACT(
						EPOCH
						FROM
							(T.TYPED_END_TIME - T.TYPED_START_TIME)
					) / 60
				) THEN 'downtime_duration_mismatch'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	MAINTENANCE_ID,
	WORK_STATION_ID,
	OPERATOR_ID,
	MAINTENANCE_TYPE,
	DOWNTIME_REASON,
	RAW_START_TIME,
	RAW_END_TIME,
	RAW_DOWNTIME_MIN,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;

INSERT INTO
	AUDIT.PUNCHING_TELEMETRY_REJECTED (
		TELEMETRY_ID,
		TIMESTAMP,
		WORK_STATION_ID,
		OPERATOR_ID,
		SHIFT,
		MACHINE_STATUS,
		SPINDLE_SPEED_RPM,
		FEED_RATE_MM_MIN,
		VIBRATION_G,
		TEMPERATURE_C,
		POWER_KW,
		TOOL_WEAR_PCT,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			TELEMETRY_ID,
			TIMESTAMP,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			MACHINE_STATUS,
			SPINDLE_SPEED_RPM,
			FEED_RATE_MM_MIN,
			VIBRATION_G,
			TEMPERATURE_C,
			POWER_KW,
			TOOL_WEAR_PCT,
			CASE
				WHEN TIMESTAMP ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN TIMESTAMP::TIMESTAMP
			END AS TYPED_TIMESTAMP,
			CASE
				WHEN SPINDLE_SPEED_RPM ~ '^-?\d+(\.\d+)?$' THEN SPINDLE_SPEED_RPM::NUMERIC
			END AS TYPED_SPINDLE_SPEED_RPM,
			CASE
				WHEN FEED_RATE_MM_MIN ~ '^-?\d+(\.\d+)?$' THEN FEED_RATE_MM_MIN::NUMERIC
			END AS TYPED_FEED_RATE_MM_MIN,
			CASE
				WHEN VIBRATION_G ~ '^-?\d+(\.\d+)?$' THEN VIBRATION_G::NUMERIC
			END AS TYPED_VIBRATION_G,
			CASE
				WHEN TEMPERATURE_C ~ '^-?\d+(\.\d+)?$' THEN TEMPERATURE_C::NUMERIC
			END AS TYPED_TEMPERATURE_C,
			CASE
				WHEN POWER_KW ~ '^-?\d+(\.\d+)?$' THEN POWER_KW::NUMERIC
			END AS TYPED_POWER_KW,
			CASE
				WHEN TOOL_WEAR_PCT ~ '^-?\d+(\.\d+)?$' THEN TOOL_WEAR_PCT::NUMERIC
			END AS TYPED_TOOL_WEAR_PCT
		FROM
			STAGE.PUNCHING_TELEMETRY
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN TELEMETRY_ID IS NULL THEN 'null_telemetry_id'
				WHEN TYPED_TIMESTAMP IS NULL THEN 'null_timestamp'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS S
					WHERE
						S.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.MACHINE_STATES M
					WHERE
						M.STATUS = T.MACHINE_STATUS
				) THEN 'invalid_machine_state'
				WHEN TYPED_SPINDLE_SPEED_RPM IS NULL THEN 'null_spindle_speed'
				WHEN TYPED_FEED_RATE_MM_MIN IS NULL THEN 'null_feed_rate'
				WHEN TYPED_VIBRATION_G IS NULL THEN 'null_vibration'
				WHEN TYPED_TEMPERATURE_C IS NULL THEN 'null_temperature'
				WHEN TYPED_POWER_KW IS NULL THEN 'null_power'
				WHEN TYPED_TOOL_WEAR_PCT IS NULL THEN 'null_tool_wear'
				WHEN TYPED_SPINDLE_SPEED_RPM NOT BETWEEN 0 AND 9999.99  THEN 'invalid_spindle_speed'
				WHEN TYPED_FEED_RATE_MM_MIN NOT BETWEEN 0 AND 9999.99  THEN 'invalid_feed_rate'
				WHEN TYPED_VIBRATION_G NOT BETWEEN 0 AND 9.99  THEN 'invalid_vibration'
				WHEN TYPED_TEMPERATURE_C NOT BETWEEN 0 AND 99.99  THEN 'invalid_temperature'
				WHEN TYPED_POWER_KW NOT BETWEEN 0 AND 99.99  THEN 'invalid_power'
				WHEN TYPED_TOOL_WEAR_PCT NOT BETWEEN 0 AND 99.99  THEN 'invalid_tool_wear'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	TELEMETRY_ID,
	TIMESTAMP,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	MACHINE_STATUS,
	SPINDLE_SPEED_RPM,
	FEED_RATE_MM_MIN,
	VIBRATION_G,
	TEMPERATURE_C,
	POWER_KW,
	TOOL_WEAR_PCT,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;

INSERT INTO
	AUDIT.BENDING_TELEMETRY_REJECTED (
		TELEMETRY_ID,
		TIMESTAMP,
		WORK_STATION_ID,
		OPERATOR_ID,
		SHIFT,
		MACHINE_STATUS,
		BEND_ANGLE_DEG,
		HYDRAULIC_PRESSURE_BAR,
		FORCE_TON,
		CYCLE_TIME_SEC,
		POWER_KW,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			TELEMETRY_ID,
			TIMESTAMP,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			MACHINE_STATUS,
			BEND_ANGLE_DEG,
			HYDRAULIC_PRESSURE_BAR,
			FORCE_TON,
			CYCLE_TIME_SEC,
			POWER_KW,
			CASE
				WHEN TIMESTAMP ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN TIMESTAMP::TIMESTAMP
			END AS TYPED_TIMESTAMP,
			CASE
				WHEN BEND_ANGLE_DEG ~ '^-?\d+(\.\d+)?$' THEN BEND_ANGLE_DEG::NUMERIC
			END AS TYPED_BEND_ANGLE_DEG,
			CASE
				WHEN HYDRAULIC_PRESSURE_BAR ~ '^-?\d+(\.\d+)?$' THEN HYDRAULIC_PRESSURE_BAR::NUMERIC
			END AS TYPED_HYDRAULIC_PRESSURE_BAR,
			CASE
				WHEN FORCE_TON ~ '^-?\d+(\.\d+)?$' THEN FORCE_TON::NUMERIC
			END AS TYPED_FORCE_TON,
			CASE
				WHEN CYCLE_TIME_SEC ~ '^-?\d+(\.\d+)?$' THEN CYCLE_TIME_SEC::NUMERIC
			END AS TYPED_CYCLE_TIME_SEC,
			CASE
				WHEN POWER_KW ~ '^-?\d+(\.\d+)?$' THEN POWER_KW::NUMERIC
			END AS TYPED_POWER_KW
		FROM
			STAGE.BENDING_TELEMETRY
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN TELEMETRY_ID IS NULL THEN 'null_telemetry_id'
				WHEN TYPED_TIMESTAMP IS NULL THEN 'null_timestamp'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS S
					WHERE
						S.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.MACHINE_STATES M
					WHERE
						M.STATUS = T.MACHINE_STATUS
				) THEN 'invalid_machine_state'
				WHEN TYPED_BEND_ANGLE_DEG IS NULL THEN 'null_bend_angle'
				WHEN TYPED_HYDRAULIC_PRESSURE_BAR IS NULL THEN 'null_hydraulic_pressure'
				WHEN TYPED_FORCE_TON IS NULL THEN 'null_force_ton'
				WHEN TYPED_CYCLE_TIME_SEC IS NULL THEN 'null_cycle_time'
				WHEN TYPED_POWER_KW IS NULL THEN 'null_power'
				WHEN TYPED_BEND_ANGLE_DEG NOT BETWEEN 0 AND 99.99  THEN 'invalid_bend_angle'
				WHEN TYPED_HYDRAULIC_PRESSURE_BAR NOT BETWEEN 0 AND 999.99  THEN 'invalid_hydraulic_pressure'
				WHEN TYPED_FORCE_TON NOT BETWEEN 0 AND 999.99  THEN 'invalid_force_ton'
				WHEN TYPED_CYCLE_TIME_SEC NOT BETWEEN 0 AND 999.99  THEN 'invalid_cycle_time'
				WHEN TYPED_POWER_KW NOT BETWEEN 0 AND 99.99  THEN 'invalid_power'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	TELEMETRY_ID,
	TIMESTAMP,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	MACHINE_STATUS,
	BEND_ANGLE_DEG,
	HYDRAULIC_PRESSURE_BAR,
	FORCE_TON,
	CYCLE_TIME_SEC,
	POWER_KW,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;

INSERT INTO
	AUDIT.WELDING_TELEMETRY_REJECTED (
		TELEMETRY_ID,
		TIMESTAMP,
		WORK_STATION_ID,
		OPERATOR_ID,
		SHIFT,
		MACHINE_STATUS,
		WELDING_CURRENT_AMP,
		WELDING_VOLTAGE_V,
		GAS_FLOW_L_MIN,
		WIRE_FEED_SPEED_M_MIN,
		TEMPERATURE_C,
		POWER_KW,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			TELEMETRY_ID,
			TIMESTAMP,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			MACHINE_STATUS,
			WELDING_CURRENT_AMP,
			WELDING_VOLTAGE_V,
			GAS_FLOW_L_MIN,
			WIRE_FEED_SPEED_M_MIN,
			TEMPERATURE_C,
			POWER_KW,
			CASE
				WHEN TIMESTAMP ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN TIMESTAMP::TIMESTAMP
			END AS TYPED_TIMESTAMP,
			CASE
				WHEN WELDING_CURRENT_AMP ~ '^-?\d+(\.\d+)?$' THEN WELDING_CURRENT_AMP::NUMERIC
			END AS TYPED_WELDING_CURRENT_AMP,
			CASE
				WHEN WELDING_VOLTAGE_V ~ '^-?\d+(\.\d+)?$' THEN WELDING_VOLTAGE_V::NUMERIC
			END AS TYPED_WELDING_VOLTAGE_V,
			CASE
				WHEN GAS_FLOW_L_MIN ~ '^-?\d+(\.\d+)?$' THEN GAS_FLOW_L_MIN::NUMERIC
			END AS TYPED_GAS_FLOW_L_MIN,
			CASE
				WHEN WIRE_FEED_SPEED_M_MIN ~ '^-?\d+(\.\d+)?$' THEN WIRE_FEED_SPEED_M_MIN::NUMERIC
			END AS TYPED_WIRE_FEED_SPEED_M_MIN,
			CASE
				WHEN TEMPERATURE_C ~ '^-?\d+(\.\d+)?$' THEN TEMPERATURE_C::NUMERIC
			END AS TYPED_TEMPERATURE_C,
			CASE
				WHEN POWER_KW ~ '^-?\d+(\.\d+)?$' THEN POWER_KW::NUMERIC
			END AS TYPED_POWER_KW
		FROM
			STAGE.WELDING_TELEMETRY
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN TELEMETRY_ID IS NULL THEN 'null_telemetry_id'
				WHEN TYPED_TIMESTAMP IS NULL THEN 'null_timestamp'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS S
					WHERE
						S.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.MACHINE_STATES M
					WHERE
						M.STATUS = T.MACHINE_STATUS
				) THEN 'invalid_machine_state'
				WHEN TYPED_WELDING_CURRENT_AMP IS NULL THEN 'null_welding_current'
				WHEN TYPED_WELDING_VOLTAGE_V IS NULL THEN 'null_welding_voltage'
				WHEN TYPED_GAS_FLOW_L_MIN IS NULL THEN 'null_gas_flow'
				WHEN TYPED_WIRE_FEED_SPEED_M_MIN IS NULL THEN 'null_wire_feed_speed'
				WHEN TYPED_TEMPERATURE_C IS NULL THEN 'null_temperature'
				WHEN TYPED_POWER_KW IS NULL THEN 'null_power'
				WHEN TYPED_WELDING_CURRENT_AMP NOT BETWEEN 0 AND 999.99  THEN 'invalid_welding_current'
				WHEN TYPED_WELDING_VOLTAGE_V NOT BETWEEN 0 AND 99.99  THEN 'invalid_welding_voltage'
				WHEN TYPED_GAS_FLOW_L_MIN NOT BETWEEN 0 AND 99.99  THEN 'invalid_gas_flow'
				WHEN TYPED_WIRE_FEED_SPEED_M_MIN NOT BETWEEN 0 AND 99.99  THEN 'invalid_wire_feed_speed'
				WHEN TYPED_TEMPERATURE_C NOT BETWEEN 0 AND 999.99  THEN 'invalid_temperature'
				WHEN TYPED_POWER_KW NOT BETWEEN 0 AND 99.99  THEN 'invalid_power'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	TELEMETRY_ID,
	TIMESTAMP,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	MACHINE_STATUS,
	WELDING_CURRENT_AMP,
	WELDING_VOLTAGE_V,
	GAS_FLOW_L_MIN,
	WIRE_FEED_SPEED_M_MIN,
	TEMPERATURE_C,
	POWER_KW,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;

INSERT INTO
	AUDIT.POWDER_COATING_TELEMETRY_REJECTED (
		TELEMETRY_ID,
		TIMESTAMP,
		WORK_STATION_ID,
		OPERATOR_ID,
		SHIFT,
		MACHINE_STATUS,
		OVEN_TEMPERATURE_C,
		CONVEYOR_SPEED_M_MIN,
		POWDER_FLOW_G_MIN,
		AIR_PRESSURE_BAR,
		HUMIDITY_PCT,
		POWER_KW,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			TELEMETRY_ID,
			TIMESTAMP,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			MACHINE_STATUS,
			OVEN_TEMPERATURE_C,
			CONVEYOR_SPEED_M_MIN,
			POWDER_FLOW_G_MIN,
			AIR_PRESSURE_BAR,
			HUMIDITY_PCT,
			POWER_KW,
			CASE
				WHEN TIMESTAMP ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN TIMESTAMP::TIMESTAMP
			END AS TYPED_TIMESTAMP,
			CASE
				WHEN OVEN_TEMPERATURE_C ~ '^-?\d+(\.\d+)?$' THEN OVEN_TEMPERATURE_C::NUMERIC
			END AS TYPED_OVEN_TEMPERATURE_C,
			CASE
				WHEN CONVEYOR_SPEED_M_MIN ~ '^-?\d+(\.\d+)?$' THEN CONVEYOR_SPEED_M_MIN::NUMERIC
			END AS TYPED_CONVEYOR_SPEED_M_MIN,
			CASE
				WHEN POWDER_FLOW_G_MIN ~ '^-?\d+(\.\d+)?$' THEN POWDER_FLOW_G_MIN::NUMERIC
			END AS TYPED_POWDER_FLOW_G_MIN,
			CASE
				WHEN AIR_PRESSURE_BAR ~ '^-?\d+(\.\d+)?$' THEN AIR_PRESSURE_BAR::NUMERIC
			END AS TYPED_AIR_PRESSURE_BAR,
			CASE
				WHEN HUMIDITY_PCT ~ '^-?\d+(\.\d+)?$' THEN HUMIDITY_PCT::NUMERIC
			END AS TYPED_HUMIDITY_PCT,
			CASE
				WHEN POWER_KW ~ '^-?\d+(\.\d+)?$' THEN POWER_KW::NUMERIC
			END AS TYPED_POWER_KW
		FROM
			STAGE.POWDER_COATING_TELEMETRY
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN TELEMETRY_ID IS NULL THEN 'null_telemetry_id'
				WHEN TYPED_TIMESTAMP IS NULL THEN 'null_timestamp'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS S
					WHERE
						S.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.MACHINE_STATES M
					WHERE
						M.STATUS = T.MACHINE_STATUS
				) THEN 'invalid_machine_state'
				WHEN TYPED_OVEN_TEMPERATURE_C IS NULL THEN 'null_oven_temperature'
				WHEN TYPED_CONVEYOR_SPEED_M_MIN IS NULL THEN 'null_conveyor_speed'
				WHEN TYPED_POWDER_FLOW_G_MIN IS NULL THEN 'null_powder_flow'
				WHEN TYPED_AIR_PRESSURE_BAR IS NULL THEN 'null_air_pressure'
				WHEN TYPED_HUMIDITY_PCT IS NULL THEN 'null_humidity'
				WHEN TYPED_POWER_KW IS NULL THEN 'null_power'
				WHEN TYPED_OVEN_TEMPERATURE_C NOT BETWEEN 0 AND 999.99  THEN 'invalid_oven_temperature'
				WHEN TYPED_CONVEYOR_SPEED_M_MIN NOT BETWEEN 0 AND 9.99  THEN 'invalid_conveyor_speed'
				WHEN TYPED_POWDER_FLOW_G_MIN NOT BETWEEN 0 AND 999.99  THEN 'invalid_powder_flow'
				WHEN TYPED_AIR_PRESSURE_BAR NOT BETWEEN 0 AND 9.99  THEN 'invalid_air_pressure'
				WHEN TYPED_HUMIDITY_PCT NOT BETWEEN 0 AND 99.99  THEN 'invalid_humidity'
				WHEN TYPED_POWER_KW NOT BETWEEN 0 AND 99.99  THEN 'invalid_power'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	TELEMETRY_ID,
	TIMESTAMP,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	MACHINE_STATUS,
	OVEN_TEMPERATURE_C,
	CONVEYOR_SPEED_M_MIN,
	POWDER_FLOW_G_MIN,
	AIR_PRESSURE_BAR,
	HUMIDITY_PCT,
	POWER_KW,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;

INSERT INTO
	AUDIT.PACKAGING_TELEMETRY_REJECTED (
		TELEMETRY_ID,
		TIMESTAMP,
		WORK_STATION_ID,
		OPERATOR_ID,
		SHIFT,
		MACHINE_STATUS,
		UNITS_PACKED_PER_MIN,
		BARCODE_SCAN_SUCCESS_RATE,
		LABEL_PRINTER_TEMP_C,
		AIR_PRESSURE_BAR,
		CONVEYOR_SPEED_M_MIN,
		POWER_KW,
		REJECTION_REASON
	)
WITH
	TYPED AS (
		SELECT
			TELEMETRY_ID,
			TIMESTAMP,
			WORK_STATION_ID,
			OPERATOR_ID,
			SHIFT,
			MACHINE_STATUS,
			UNITS_PACKED_PER_MIN,
			BARCODE_SCAN_SUCCESS_RATE,
			LABEL_PRINTER_TEMP_C,
			AIR_PRESSURE_BAR,
			CONVEYOR_SPEED_M_MIN,
			POWER_KW,
			CASE
				WHEN TIMESTAMP ~ '^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]) ([01]\d|2[0-3]):[0-5]\d:[0-5]\d$' THEN TIMESTAMP::TIMESTAMP
			END AS TYPED_TIMESTAMP,
			CASE
				WHEN UNITS_PACKED_PER_MIN ~ '^-?\d+(\.\d+)?$' THEN UNITS_PACKED_PER_MIN::NUMERIC
			END AS TYPED_UNITS_PACKED_PER_MIN,
			CASE
				WHEN BARCODE_SCAN_SUCCESS_RATE ~ '^-?\d+(\.\d+)?$' THEN BARCODE_SCAN_SUCCESS_RATE::NUMERIC
			END AS TYPED_BARCODE_SCAN_SUCCESS_RATE,
			CASE
				WHEN LABEL_PRINTER_TEMP_C ~ '^-?\d+(\.\d+)?$' THEN LABEL_PRINTER_TEMP_C::NUMERIC
			END AS TYPED_LABEL_PRINTER_TEMP_C,
			CASE
				WHEN AIR_PRESSURE_BAR ~ '^-?\d+(\.\d+)?$' THEN AIR_PRESSURE_BAR::NUMERIC
			END AS TYPED_AIR_PRESSURE_BAR,
			CASE
				WHEN CONVEYOR_SPEED_M_MIN ~ '^-?\d+(\.\d+)?$' THEN CONVEYOR_SPEED_M_MIN::NUMERIC
			END AS TYPED_CONVEYOR_SPEED_M_MIN,
			CASE
				WHEN POWER_KW ~ '^-?\d+(\.\d+)?$' THEN POWER_KW::NUMERIC
			END AS TYPED_POWER_KW
		FROM
			STAGE.PACKAGING_TELEMETRY
	),
	REJECTED AS (
		SELECT
			T.*,
			CASE
				WHEN TELEMETRY_ID IS NULL THEN 'null_telemetry_id'
				WHEN TYPED_TIMESTAMP IS NULL THEN 'null_timestamp'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.WORK_STATIONS W
					WHERE
						W.WORK_STATION_ID = T.WORK_STATION_ID
				) THEN 'invalid_work_station'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.OPERATORS O
					WHERE
						O.OPERATOR_ID = T.OPERATOR_ID
				) THEN 'invalid_operator'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.SHIFTS S
					WHERE
						S.SHIFT = T.SHIFT
				) THEN 'invalid_shift'
				WHEN NOT EXISTS (
					SELECT
						1
					FROM
						CLEAN.MACHINE_STATES M
					WHERE
						M.STATUS = T.MACHINE_STATUS
				) THEN 'invalid_machine_state'
				WHEN TYPED_UNITS_PACKED_PER_MIN IS NULL THEN 'null_units_packed'
				WHEN TYPED_BARCODE_SCAN_SUCCESS_RATE IS NULL THEN 'null_barcode_scan'
				WHEN TYPED_LABEL_PRINTER_TEMP_C IS NULL THEN 'null_label_printer_temp'
				WHEN TYPED_AIR_PRESSURE_BAR IS NULL THEN 'null_air_pressure'
				WHEN TYPED_CONVEYOR_SPEED_M_MIN IS NULL THEN 'null_conveyor_speed'
				WHEN TYPED_POWER_KW IS NULL THEN 'null_power'
				WHEN TYPED_UNITS_PACKED_PER_MIN NOT BETWEEN 0 AND 9.99  THEN 'invalid_units_packed'
				WHEN TYPED_BARCODE_SCAN_SUCCESS_RATE NOT BETWEEN 0 AND 99.99  THEN 'invalid_barcode_scan'
				WHEN TYPED_LABEL_PRINTER_TEMP_C NOT BETWEEN 0 AND 99.99  THEN 'invalid_label_printer_temp'
				WHEN TYPED_AIR_PRESSURE_BAR NOT BETWEEN 0 AND 9.99  THEN 'invalid_air_pressure'
				WHEN TYPED_CONVEYOR_SPEED_M_MIN NOT BETWEEN 0 AND 9.99  THEN 'invalid_conveyor_speed'
				WHEN TYPED_POWER_KW NOT BETWEEN 0 AND 9.99  THEN 'invalid_power'
				ELSE NULL
			END AS REJECTION_REASON
		FROM
			TYPED T
	)
SELECT
	TELEMETRY_ID,
	TIMESTAMP,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	MACHINE_STATUS,
	UNITS_PACKED_PER_MIN,
	BARCODE_SCAN_SUCCESS_RATE,
	LABEL_PRINTER_TEMP_C,
	AIR_PRESSURE_BAR,
	CONVEYOR_SPEED_M_MIN,
	POWER_KW,
	REJECTION_REASON
FROM
	REJECTED
WHERE
	REJECTION_REASON IS NOT NULL;