CREATE SCHEMA MARTS;

CREATE TABLE MARTS.DIM_MACHINE_STATES AS
SELECT
	STATUS,
	MEANING
FROM
	CLEAN.MACHINE_STATES;

CREATE TABLE MARTS.DIM_OPERATORS AS
SELECT
	OPERATOR_ID,
	NAME,
	ASSIGNED_STATION_ID,
	ASSIGNED_STATION,
	SKILL_LEVEL,
	SHIFT
FROM
	CLEAN.OPERATORS;

CREATE TABLE MARTS.DIM_PRODUCTS AS
SELECT
	PRODUCT_ID,
	PRODUCT_NAME,
	STANDARD_CYCLE_TIME_SEC,
	TARGET_SCRAP_RATE
FROM
	CLEAN.PRODUCTS;

CREATE TABLE MARTS.DIM_SHIFTS AS
SELECT
	SHIFT,
	START_TIME,
	END_TIME
FROM
	CLEAN.SHIFTS;

CREATE TABLE MARTS.DIM_WORK_STATIONS AS
SELECT
	WORK_STATION_ID,
	WORK_STATION
FROM
	CLEAN.WORK_STATIONS;

CREATE TABLE MARTS.FACT_PRODUCTION_ORDERS AS
SELECT
	ORDER_ID,
	PRODUCT_ID,
	WORK_STATION_ID,
	OPERATOR_ID,
	SHIFT,
	START_TIME,
	END_TIME,
	PLANNED_QTY,
	ACTUAL_QTY,
	SCRAP_QTY,
	ACTUAL_QTY - SCRAP_QTY AS GOOD_QTY,
	ROUND(
		EXTRACT(
			EPOCH
			FROM
				(END_TIME - START_TIME)
		) / 60.0,
		2
	) AS PRODUCTION_MINUTES
FROM
	CLEAN.PRODUCTION_ORDERS;

CREATE TABLE MARTS.FACT_MAINTENANCE_EVENTS AS
SELECT
	MAINTENANCE_ID,
	WORK_STATION_ID,
	OPERATOR_ID,
	MAINTENANCE_TYPE,
	DOWNTIME_REASON,
	START_TIME,
	END_TIME,
	DOWNTIME_MIN
FROM
	CLEAN.MAINTENANCE_EVENTS;

CREATE TABLE MARTS.FACT_MACHINE_STATUS_HOURLY AS
SELECT
	DATE_TRUNC('hour', TIMESTAMP) AS HOUR_START,
	PROCESS,
	WORK_STATION_ID,
	MACHINE_STATUS,
	ROUND(COUNT(*) * 10.0 / 60.0, 2) AS MINUTES_IN_STATUS
FROM
	(
		SELECT
			'PUNCHING' AS PROCESS,
			TIMESTAMP,
			WORK_STATION_ID,
			MACHINE_STATUS
		FROM
			CLEAN.PUNCHING_TELEMETRY
		UNION ALL
		SELECT
			'BENDING',
			TIMESTAMP,
			WORK_STATION_ID,
			MACHINE_STATUS
		FROM
			CLEAN.BENDING_TELEMETRY
		UNION ALL
		SELECT
			'WELDING',
			TIMESTAMP,
			WORK_STATION_ID,
			MACHINE_STATUS
		FROM
			CLEAN.WELDING_TELEMETRY
		UNION ALL
		SELECT
			'POWDER COATING',
			TIMESTAMP,
			WORK_STATION_ID,
			MACHINE_STATUS
		FROM
			CLEAN.POWDER_COATING_TELEMETRY
		UNION ALL
		SELECT
			'PACKAGING',
			TIMESTAMP,
			WORK_STATION_ID,
			MACHINE_STATUS
		FROM
			CLEAN.PACKAGING_TELEMETRY
	)
GROUP BY
	DATE_TRUNC('hour', TIMESTAMP),
	PROCESS,
	WORK_STATION_ID,
	MACHINE_STATUS;

CREATE VIEW MARTS.VW_OEE_BY_STATION_HOUR AS
WITH
	STATUS_PIVOT AS (
		SELECT
			HOUR_START,
			WORK_STATION_ID,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'RUNNING' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS RUNNING_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'DOWN' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS DOWN_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'IDLE' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS IDLE_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'SETUP' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS SETUP_MIN,
			SUM(MINUTES_IN_STATUS) AS TOTAL_OBSERVED_MIN
		FROM
			MARTS.FACT_MACHINE_STATUS_HOURLY
		GROUP BY
			HOUR_START,
			WORK_STATION_ID
	)
SELECT
	HOUR_START,
	WORK_STATION_ID,
	ROUND(RUNNING_MIN, 2) AS RUNNING_MIN,
	ROUND(DOWN_MIN, 2) AS DOWN_MIN,
	ROUND(IDLE_MIN, 2) AS IDLE_MIN,
	ROUND(SETUP_MIN, 2) AS SETUP_MIN,
	ROUND(TOTAL_OBSERVED_MIN, 2) AS TOTAL_OBSERVED_MIN,
	ROUND(RUNNING_MIN / TOTAL_OBSERVED_MIN, 2) AS AVAILABILITY
FROM
	STATUS_PIVOT
ORDER BY
	HOUR_START;

CREATE VIEW MARTS.VW_DOWNTIME_BY_REASON AS
SELECT
	WORK_STATION_ID,
	DOWNTIME_REASON,
	COUNT(*) AS EVENT_COUNT,
	SUM(DOWNTIME_MIN) AS TOTAL_DOWNTIME_MIN,
	ROUND(AVG(DOWNTIME_MIN), 2) AS AVG_DOWNTIME_MIN
FROM
	MARTS.FACT_MAINTENANCE_EVENTS
WHERE
	DOWNTIME_REASON IS NOT NULL
GROUP BY
	WORK_STATION_ID,
	DOWNTIME_REASON
ORDER BY
	TOTAL_DOWNTIME_MIN DESC;

CREATE TABLE MARTS.FACT_THROUGHPUT_MONTHLY AS
SELECT
	DATE_TRUNC('month', START_TIME)::DATE AS MONTH_START,
	WORK_STATION_ID,
	SHIFT,
	SUM(GOOD_QTY) AS GOOD_QTY,
	SUM(PRODUCTION_MINUTES) AS PRODUCTION_MINUTES,
	ROUND(
		SUM(GOOD_QTY)::NUMERIC / NULLIF(SUM(PRODUCTION_MINUTES) / 60, 0),
		4
	) AS THROUGHPUT_UNITS_PER_HOUR
FROM
	MARTS.FACT_PRODUCTION_ORDERS
GROUP BY
	DATE_TRUNC('month', START_TIME),
	WORK_STATION_ID,
	SHIFT
ORDER BY
	MONTH_START,
	SHIFT,
	WORK_STATION_ID;

CREATE TABLE MARTS.FACT_QUALITY_MONTHLY AS
SELECT
	DATE_TRUNC('month', START_TIME)::DATE AS MONTH_START,
	WORK_STATION_ID,
	SHIFT,
	SUM(ACTUAL_QTY) AS TOTAL_QTY,
	SUM(GOOD_QTY) AS GOOD_QTY,
	SUM(SCRAP_QTY) AS SCRAP_QTY,
	ROUND(
		SUM(GOOD_QTY)::NUMERIC / NULLIF(SUM(ACTUAL_QTY), 0),
		4
	) AS QUALITY,
	ROUND(
		SUM(SCRAP_QTY)::NUMERIC / NULLIF(SUM(ACTUAL_QTY), 0),
		4
	) AS SCRAP_RATE
FROM
	MARTS.FACT_PRODUCTION_ORDERS
GROUP BY
	DATE_TRUNC('month', START_TIME),
	WORK_STATION_ID,
	SHIFT
ORDER BY
	MONTH_START,
	SHIFT,
	WORK_STATION_ID;

CREATE TABLE MARTS.FACT_OEE_HOURLY AS
WITH
	STATUS_PIVOT AS (
		SELECT
			HOUR_START,
			WORK_STATION_ID,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'RUNNING' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS RUNNING_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'DOWN' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS DOWN_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'IDLE' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS IDLE_MIN,
			SUM(
				CASE
					WHEN MACHINE_STATUS = 'SETUP' THEN MINUTES_IN_STATUS
					ELSE 0
				END
			) AS SETUP_MIN,
			SUM(MINUTES_IN_STATUS) AS PLANNED_PROD_MIN
		FROM
			MARTS.FACT_MACHINE_STATUS_HOURLY
		GROUP BY
			HOUR_START,
			WORK_STATION_ID
	),
	PRODUCTION_HOURLY AS (
		SELECT
			DATE_TRUNC('hour', P.START_TIME) AS HOUR_START,
			P.WORK_STATION_ID,
			SUM(P.ACTUAL_QTY) AS TOTAL_QTY,
			SUM(P.GOOD_QTY) AS GOOD_QTY,
			SUM(P.ACTUAL_QTY * O.IDEAL_CYCLE_TIME_SEC / 60.0) AS IDEAL_PRODUCTION_MINUTES
		FROM
			MARTS.FACT_PRODUCTION_ORDERS P
			JOIN CLEAN.PRODUCTS PR ON PR.PRODUCT_ID = P.PRODUCT_ID
			JOIN CLEAN.OPERATIONS O ON O.WORK_STATION_ID = P.WORK_STATION_ID
			AND O.PRODUCT_NAME = PR.PRODUCT_NAME
		GROUP BY
			DATE_TRUNC('hour', P.START_TIME),
			P.WORK_STATION_ID
	)
SELECT
	S.HOUR_START,
	S.WORK_STATION_ID,
	S.RUNNING_MIN,
	S.DOWN_MIN,
	S.IDLE_MIN,
	S.SETUP_MIN,
	S.PLANNED_PROD_MIN,
	COALESCE(P.TOTAL_QTY, 0) AS TOTAL_QTY,
	COALESCE(P.GOOD_QTY, 0) AS GOOD_QTY,
	ROUND(S.RUNNING_MIN / NULLIF(S.PLANNED_PROD_MIN, 0), 2) AS AVAILABILITY,
	ROUND(
		COALESCE(P.IDEAL_PRODUCTION_MINUTES, 0) / NULLIF(S.RUNNING_MIN, 0),
		4
	) AS PERFORMANCE,
	ROUND(
		COALESCE(P.GOOD_QTY, 0)::NUMERIC / NULLIF(P.TOTAL_QTY, 0),
		4
	) AS QUALITY,
	ROUND(
		(S.RUNNING_MIN / NULLIF(S.PLANNED_PROD_MIN, 0)) * (
			COALESCE(P.IDEAL_PRODUCTION_MINUTES, 0) / NULLIF(S.RUNNING_MIN, 0)
		) * (
			COALESCE(P.GOOD_QTY, 0)::NUMERIC / NULLIF(P.TOTAL_QTY, 0)
		),
		4
	) AS OEE
FROM
	STATUS_PIVOT S
	JOIN PRODUCTION_HOURLY P ON P.HOUR_START = S.HOUR_START
	AND P.WORK_STATION_ID = S.WORK_STATION_ID
WHERE
	ROUND(COALESCE(P.IDEAL_PRODUCTION_MINUTES, 0) / NULLIF(S.RUNNING_MIN, 0),2) <= 1
ORDER BY
	S.HOUR_START,
	S.WORK_STATION_ID;

CREATE TABLE MARTS.FACT_DOWNTIME_MONTHLY AS
SELECT
	DATE_TRUNC('month', START_TIME)::DATE AS MONTH_START,
	WORK_STATION_ID,
	MAINTENANCE_TYPE,
	DOWNTIME_REASON,
	COUNT(*) AS DOWNTIME_EVENTS,
	SUM(DOWNTIME_MIN) AS TOTAL_DOWNTIME_MIN,
	ROUND(AVG(DOWNTIME_MIN), 2) AS AVG_DOWNTIME_MIN
FROM
	MARTS.FACT_MAINTENANCE_EVENTS
WHERE
	DOWNTIME_REASON IS NOT NULL
GROUP BY
	DATE_TRUNC('month', START_TIME),
	WORK_STATION_ID,
	MAINTENANCE_TYPE,
	DOWNTIME_REASON;

CREATE TABLE MARTS.FACT_OPERATOR_PERFORMANCE AS
SELECT
    DATE_TRUNC('month', START_TIME)::DATE AS MONTH,
    OPERATOR_ID,
    WORK_STATION_ID,
    SHIFT,
    COUNT(*) AS ORDER_COUNT,
    SUM(PLANNED_QTY) AS PLANNED_QTY,
    SUM(ACTUAL_QTY) AS ACTUAL_QTY,
    SUM(GOOD_QTY) AS GOOD_QTY,
    SUM(SCRAP_QTY) AS SCRAP_QTY,
    SUM(PRODUCTION_MINUTES) AS PRODUCTION_MINUTES,
    ROUND(
        SUM(GOOD_QTY)::NUMERIC / NULLIF(SUM(PRODUCTION_MINUTES) / 60.0, 0),
        4
    ) AS UNITS_PER_HOUR,
    ROUND(
        SUM(SCRAP_QTY)::NUMERIC / NULLIF(SUM(ACTUAL_QTY), 0),
        4
    ) AS SCRAP_RATE
FROM
    MARTS.FACT_PRODUCTION_ORDERS
GROUP BY
    DATE_TRUNC('month', START_TIME)::DATE,
    OPERATOR_ID,
    WORK_STATION_ID,
    SHIFT;

CREATE VIEW MARTS.VW_FACTORY_KPI_CARDS AS
SELECT
	SUM(ACTUAL_QTY) AS TOTAL_UNITS,
	SUM(GOOD_QTY) AS GOOD_UNITS,
	SUM(SCRAP_QTY) AS SCRAP_UNITS,
	ROUND(
		SUM(SCRAP_QTY)::NUMERIC / NULLIF(SUM(ACTUAL_QTY), 0),
		4
	) AS SCRAP_RATE,
	ROUND(
		SUM(GOOD_QTY)::NUMERIC / NULLIF(SUM(ACTUAL_QTY), 0),
		4
	) AS QUALITY_RATE,
	ROUND(
		SUM(GOOD_QTY)::NUMERIC / NULLIF(SUM(PRODUCTION_MINUTES) / 60.0, 0),
		2
	) AS THROUGHPUT_UNITS_PER_HOUR
FROM
	MARTS.FACT_PRODUCTION_ORDERS;